# Generated by Django 3.2.4 on 2021-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(default='This is the introduction.'),
        ),
    ]
