# Generated by Django 3.2.4 on 2021-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='This is the body.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.CharField(default='This is the introduction.', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(default='Subject', max_length=200),
        ),
    ]
