# Generated by Django 3.2.4 on 2021-06-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210630_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph',
            field=models.TextField(default='This is a paragraph.'),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_title_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_title_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_title_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_title_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_title_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
