# Generated by Django 3.2.4 on 2021-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210630_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quote',
            field=models.TextField(blank=True),
        ),
    ]
