# Generated by Django 3.2.4 on 2021-07-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210630_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject_date',
            field=models.DateTimeField(blank=True, default='July 01, 2021'),
        ),
    ]
