# Generated by Django 3.2.4 on 2021-07-01 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_subject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 1, 21, 11, 21, 3509)),
        ),
    ]
