# Generated by Django 3.2.4 on 2021-07-03 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_subject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 3, 19, 7, 51, 345041)),
        ),
    ]
