# Generated by Django 3.2.4 on 2021-08-03 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_subject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
