# Generated by Django 3.2.4 on 2021-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='realtor',
            name='job_title',
            field=models.CharField(default='Realtor', max_length=100),
        ),
    ]
